server:
  appport: ":8088"
  apphost: "localhost"
  tlscert: "tls/go_storage.crt"
  privatekey: "tls/go_storage.key"

database:
  dbname: "postgres" 
  dbuser: "postgres"
  dbpassword: "test"
  dbhost: "localhost"